name: Seed Database

on:
  push:
    branches:
      - main
    paths:
      - "src/seed/**"
  workflow_dispatch:

env:
  db_app: bettersalesai-database
  image: registry.fly.io/bettersalesai-kickads

concurrency:
  group: deploy

jobs:
  seeds:
    name: Seed database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Setup secrets
        run: echo "$DEPLOY_SECRETS" > .env
        env:
          DEPLOY_SECRETS: ${{ secrets.DEPLOY_SECRETS }}

      - name: Install dependencies
        run : yarn install --production=false

      - name: Run seeds
        run: yarn db:seed
